# Generated by Django 4.0.1 on 2022-02-07 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_signup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='body',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='title',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='last_modified',
        ),
    ]
