# Generated by Django 4.0.1 on 2022-02-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_rename_body_signup_name_rename_title_signup_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='email',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
