# Generated by Django 4.0.1 on 2022-02-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_signup_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.CharField(default='False', max_length=100),
        ),
        migrations.AlterField(
            model_name='signup',
            name='name',
            field=models.CharField(default='False', max_length=100),
        ),
        migrations.AlterField(
            model_name='signup',
            name='number',
            field=models.CharField(default='False', max_length=100),
        ),
    ]
