# Generated by Django 4.0.1 on 2022-02-07 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_alter_signup_email_alter_signup_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signup',
            new_name='customerUsers',
        ),
    ]
