# Generated by Django 4.0.1 on 2022-03-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_rename_signup_customerusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerusers',
            name='password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
